[package]
name = "fluxc_errors"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
pest = "2"

fluxc_span = { path =  "../fluxc_span" }
fluxc_parser = { path =  "../fluxc_parser" }
