[package]
name = "styxc_parser"
version = "0.0.0"
authors = ["SkyezerFox <actuallyori@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1"
pest_derive = "2.1"

styxc_ast = { path =  "../styxc_ast" }
