[package]
name = "styxc"
version = "0.1.0"
authors = ["SkyezerFox <actuallyori@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.6"
clap = "3.0.0-beta.2"
env_logger = "0.8"
log = "0.4"
