[package]
name = "styxc"
version = "0.1.0"
authors = ["SkyezerFox <actuallyori@gmail.com>"]
edition = "2018"

[dependencies]
annotate-snippets = "0.9"
clap = "3.0.0-beta.2"
env_logger = "0.8"
lazy_static = "1"
log = "0.4"
peg = "0.7"

[features]
trace = ["peg/trace"]
