[package]
name = "styxc_ast"
version = "0.1.0"
authors = ["SkyezerFox <actuallyori@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
# needed for Span
pest = "2"

styxc_span = { path =  "../styxc_span" }
styxc_types = { path = "../styxc_types" }
